### ISSUE TITLE
Possible performance issue on AMD Epyc 7401P CI machine

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#358] opened 2019-11-05 22:46 UTC
The [simd8 genericization patch](https://github.com/lemire/simdjson/pull/356) is showing a possible < 1% performance regression, having failed 2 times (out of a lot more) on [this CI machine](https://cloud.drone.io/lemire/simdjson/1409/2/2). If we merge that, we should come back and see if we can prove this as real or not real.

**Comment by lemire** [comment] 2019-11-05 22:51
Unless I am mistaken, this is a Zen processor. I ordered a Zen 2 (AMD EPYC 7262) which I plan to use to review our progress and identify any weak point.

**Comment by lemire** [comment] 2019-12-02 17:51
Ok. So I have an AMD EPYC 7262 8-Core Processor https://en.wikipedia.org/wiki/Zen_2

I am using GNU GCC 8.3.

I am going to compare the current master with version 0.2.1 (our last release). For each file, the first line is master, the second line our last release...

```
jsonexamples/apache_builds.json
Min:  6.0473e-05 bytes read: 127275 Gigabytes/second: 2.10466
Min:  6.2627e-05 bytes read: 127275 Gigabytes/second: 2.03227
jsonexamples/canada.json
Min:  0.00231394 bytes read: 2251051 Gigabytes/second: 0.972823
Min:  0.0023847 bytes read: 2251051 Gigabytes/second: 0.943955
jsonexamples/citm_catalog.json
Min:  0.000712827 bytes read: 1727204 Gigabytes/second: 2.42303
Min:  0.000735269 bytes read: 1727204 Gigabytes/second: 2.34908
jsonexamples/github_events.json
Min:  2.8253e-05 bytes read: 65132 Gigabytes/second: 2.30531
Min:  2.9325e-05 bytes read: 65132 Gigabytes/second: 2.22104
jsonexamples/gsoc-2018.json
Min:  0.00102524 bytes read: 3327831 Gigabytes/second: 3.2459
Min:  0.00103138 bytes read: 3327831 Gigabytes/second: 3.22657
jsonexamples/instruments.json
Min:  0.000117881 bytes read: 220346 Gigabytes/second: 1.86922
Min:  0.000118943 bytes read: 220346 Gigabytes/second: 1.85253
jsonexamples/marine_ik.json
Min:  0.00341574 bytes read: 2983466 Gigabytes/second: 0.873445
Min:  0.00340661 bytes read: 2983466 Gigabytes/second: 0.875788
jsonexamples/mesh.json
Min:  0.000812143 bytes read: 723597 Gigabytes/second: 0.890972
Min:  0.000807264 bytes read: 723597 Gigabytes/second: 0.896357
jsonexamples/mesh.pretty.json
Min:  0.00107555 bytes read: 1577353 Gigabytes/second: 1.46656
Min:  0.00108855 bytes read: 1577353 Gigabytes/second: 1.44904
jsonexamples/numbers.json
Min:  0.000137287 bytes read: 150124 Gigabytes/second: 1.0935
Min:  0.000140253 bytes read: 150124 Gigabytes/second: 1.07038
jsonexamples/random.json
Min:  0.000385613 bytes read: 510476 Gigabytes/second: 1.3238
Min:  0.000407273 bytes read: 510476 Gigabytes/second: 1.2534
jsonexamples/twitterescaped.json
Min:  0.000489969 bytes read: 562408 Gigabytes/second: 1.14784
Min:  0.000505988 bytes read: 562408 Gigabytes/second: 1.1115
jsonexamples/twitter.json
Min:  0.00030411 bytes read: 631515 Gigabytes/second: 2.0766
Min:  0.000315312 bytes read: 631515 Gigabytes/second: 2.00283
jsonexamples/update-center.json
Min:  0.000320291 bytes read: 533178 Gigabytes/second: 1.66467
Min:  0.000330239 bytes read: 533178 Gigabytes/second: 1.61452
```


As you can see, we are all around better. It is possible that between the last release and the current one, there was a performance regression, but given that we have made measurable progress since the last release, I am not concerned.

I recommend closing this issue.

**Comment by lemire** [comment] 2020-01-09 21:28
I am going to close this since I do not see an issue.

**Closed by lemire** 2020-01-09 21:28 UTC
