### ISSUE TITLE
possible bug:unsupport uint64 value

### ISSUE THREAD

**Issue by XLPE** [lemire/simdjson#178] opened 2019-05-25 14:05 UTC
passed
{"rsslim":9223372036854775807}

invalid:
{"rsslim":9223372036854775808}

**Comment by lemire** [comment] 2019-05-25 14:53
Not a bug, we do not support unsigned 64-bit ints currently:

https://github.com/lemire/simdjson/issues/68

Quoting from the README:

> We parse integers and floating-point numbers as separate types which allows us to support large 64-bit integers in [-9223372036854775808,9223372036854775808), like a Java long or a C/C++ long long. Among the parsers that differentiate between integers and floating-point numbers, not all support 64-bit integers. (For example, sajson rejects JSON files with integers larger than or equal to 2147483648. RapidJSON will parse a file containing an overly long integer like 18446744073709551616 as a floating-point number.) When we cannot represent exactly an integer as a signed 64-bit value, we reject the JSON document.


As stated in issue 68, it is reasonable to support unsigned 64-bit integers. I think we will do so in a future release.

Note that they are *not* supported in Java and JavaScript.

So, understandably, the JSON specification allows us to put limits on the kind of numbers we support.

**Comment by lemire** [comment] 2019-05-25 14:53
Closing. Reopen if I misunderstood.

**Closed by lemire** 2019-05-25 14:53 UTC
