### ISSUE TITLE
Interest in adding an case insensitive `move_to_key`?

### ISSUE THREAD

**Issue by jplauri** [lemire/simdjson#323] opened 2019-10-05 12:28 UTC
To offer a bit of robustness, it is sometimes useful to be able to find a key in an case insensitive manner (for instance, such functionality is given by libjson, now a rather outdated library). That is, if my JSON has a key like "Foo", I'd still like to be able to match it if I search for "foo". Currently, of course, `move_to_key` does not support this as it relies on `strcmp`. The functionality I describe could be achieved by replacing `strcmp` with its case insensitive variant `strcmpi`.

A clean way to add support would be to refactor `move_to_key` into an internal implementation which accepts a comparator function. Then, the public implementations of `move_to_key` and (say) `move_to_insensitive_key` would be calls to the private implementation with two different functor parameters.

Do you think it would make sense for me to make PR for this?

**Comment by lemire** [comment] 2019-10-05 12:50
This is all fine but we want to benchmark to see what the performance implications are. A runtime comparator might carry additional overhead. As it is, we want to work on further optimizing these functions, so a performance regression would be unfortunate.

I expect that the default ought to be case-sensitive matching since this is surely what the standard demands.

**Comment by jplauri** [comment] 2019-10-05 12:58
Right, so I just meant that the user could call either `move_to_key(...)` or `move_to_insensitive_key(...)`, whichever was desired.

In an ideal world, there should be no overhead. But if we were paranoid, we could just copy and paste the implementation of `move_to_key` for `move_to_insensitive_key`, but just replace `strcmp` as described. That's code duplication, but not much. Further, no benchmarking should then be required as absolutely nothing changes for `move_to_key`. 

What do you think?

**Comment by lemire** [comment] 2019-10-05 20:48
I think it is all fine.

**Comment by aqrit** [comment] 2019-10-07 16:02
Duplicate of #294 

"Case Folding"

**Comment by lemire** [comment] 2019-10-07 20:12
I am going to close this issue. The PR seems to lead to some performance regression, but I'll have to look at fixing it as a separate issue.

**Closed by lemire** 2019-10-07 20:12 UTC
