### ISSUE TITLE
valgrind uninitialised value

### ISSUE THREAD

**Issue by milipili** [lemire/simdjson#339] opened 2019-10-20 09:35 UTC
A little report from valgrind :)

```
=15076== Use of uninitialised value of size 8
==15076==    at 0x16FEAB: parse_string<(simdjson::Architecture)1> (simdjson.h:38718)
==15076==    by 0x16FEAB: int simdjson::unified_machine<(simdjson::Architecture)1>(unsigned char const*, unsigned long, simdjson::ParsedJson&) (simdjson.cpp:1029)
==15076==    by 0x17E4A6: int simdjson::json_parse_implementation<(simdjson::Architecture)1>(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (simdjson.h:39511)
==15076==    by 0x157B5A: simdjson::json_parse_dispatch(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (simdjson.cpp:431)
==15076==    by 0x157A3E: simdjson::json_parse(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (simdjson.cpp:379)
==15076==    by 0x157BBC: simdjson::build_parsed_json(unsigned char const*, unsigned long, bool) (simdjson.cpp:442)
==15076==    by 0x13266F: simdjson::build_parsed_json(char const*, unsigned long, bool) (simdjson.h:39650)
==15076==    by 0x1326B8: simdjson::build_parsed_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (simdjson.h:39672)
==15076==    by 0x130D3F: hc::grid::delegates::(anonymous namespace)::parse_json(hc::grid::delegates::(anonymous namespace)::RefreshInfo&) (refresh-mesos-info.cpp:300)
==15076==    by 0x13157F: hc::grid::delegates::Mesosd::refresh_mesos_info() (refresh-mesos-info.cpp:405)
==15076==    by 0x117FB6: hc::grid::delegates::Mesosd::start() (delegate-mesosd.cpp:33)
==15076==    by 0x11B216: main::{lambda()#3}::operator()() const (main.cpp:114)
==15076==    by 0x11EBD3: std::_Function_handler<void (), main::{lambda()#3}>::_M_invoke(std::_Any_data const&) (std_function.h:300)
==15076== 
```

**Comment by lemire** [comment] 2019-10-20 17:04
Damien: can you provide a reproducible test case? It is hard to address potential issues if we can't reproduce them.

**Comment by lemire** [comment] 2019-11-06 16:11
The submitter is invited to provide a reproducible case. I am closing this due to the lack of a reproducible case.

**Closed by lemire** 2019-11-06 16:11 UTC
