### ISSUE TITLE
Add clear error when AVX2 is not supported on the current arch

### ISSUE THREAD

**Issue by kylehovey** [lemire/simdjson#34] opened 2019-02-21 05:46 UTC
I tried running the benchmarks on my machine but got an error when running the parser. I cloned the repo, ran `cmake .`, `make`, then `make test` to get this result. See screenfetch at bottom for specs of my machine.

```shell
Test project /Users/speleo/Downloads/simdjson
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................***Exception: Illegal  0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
	  1 - jsoncheck (ILLEGAL)
Errors while running CTest
make: *** [test] Error 8
```

```shell
                    'c.          speleo@leaf.local
                 ,xNMM.          -----------------
               .OMMMMo           OS: macOS 10.14 18A391 x86_64
               OMMM0,            Host: MacBookPro10,1
     .;loddo:' loolloddol;.      Kernel: 18.0.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 7 days, 12 hours, 19 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 273
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.3
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Kwm
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Intel i7-3635QM (8) @ 2.40GHz
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Intel HD Graphics 4000, NVIDIA GeForce GT 650M
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 3678MiB / 16384MiB
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.
```

**Comment by shusso** [comment] 2019-02-21 07:57
Also can reproduce the problem in OSX, interesting though building + testing the staticlib works
```
[staticbuild] > sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.3
BuildVersion:   18D109

[simdjson] > mkdir staticbuild
[simdjson] > cd staticbuild/
[staticbuild] > cmake -DSIMDJSON_BUILD_STATIC=ON ..
...
[staticbuild] > make
..
[staticbuild] > make test
Running tests...
Test project /foobar/testing/simdjson/staticbuild
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
```

**Comment by shusso** [comment] 2019-02-21 08:04
after
```
[simdjson] > mkdir build
[simdjson] > cd build/
[build] > cmake ..
-- No build type selected, default to Release
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building a dynamic library (default).
-- SIMDJSON_LIB_TYPE: SHARED
-- Library output directory (does not apply to Visual Studio): /foobar/testing/simdjson/build
-- Configuring done
-- Generating done
-- Build files have been written to: /foobar/testing/simdjson/build
[build] > make
..
```
running the pure `ctest` I get the following behaviour
```
[build] > ctest
Test project /Users/shusso/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................Child aborted***Exception:   0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - jsoncheck (Child aborted)
Errors while running CTest
[build] > ctest
Test project /Users/shusso/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
[build] > ctest
Test project /Users/shusso/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................Child aborted***Exception:   0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - jsoncheck (Child aborted)
Errors while running CTest
[build] > ctest
Test project /Users/shusso/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
```

and then if I run the `make test` I get the following
```
[build] > make test
Running tests...
Test project /Users/shusso/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................Child aborted***Exception:   0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - jsoncheck (Child aborted)
Errors while running CTest
make: *** [test] Error 8
[build] > make test
Running tests...
Test project /Users/shusso/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
```

**Comment by shusso** [comment] 2019-02-21 08:05
after
```
[simdjson] > mkdir build
[simdjson] > cd build/
[build] > cmake ..
-- No build type selected, default to Release
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building a dynamic library (default).
-- SIMDJSON_LIB_TYPE: SHARED
-- Library output directory (does not apply to Visual Studio): /foobar/testing/simdjson/build
-- Configuring done
-- Generating done
-- Build files have been written to: /foobar/testing/simdjson/build
[build] > make
..
```
running the pure `ctest` I get the following behaviour
```
[build] > ctest
Test project /foobar/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................Child aborted***Exception:   0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - jsoncheck (Child aborted)
Errors while running CTest
[build] > ctest
Test project /foobar/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
[build] > ctest
Test project /foobar/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................Child aborted***Exception:   0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - jsoncheck (Child aborted)
Errors while running CTest
[build] > ctest
Test project /foobar/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
```

and then if I run the `make test` I get the following
```
[build] > make test
Running tests...
Test project /foobar/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................Child aborted***Exception:   0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - jsoncheck (Child aborted)
Errors while running CTest
make: *** [test] Error 8
[build] > make test
Running tests...
Test project /foobar/testing/simdjson/build
    Start 1: jsoncheck
1/1 Test #1: jsoncheck ........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
```

**Comment by lemire** [comment] 2019-02-21 13:01
@kylehovey Are you sure that your processor is a recent x64 processor with support for AVX2 instruction, so Haswell or better?

My Googling reveals that your processor was released in 2012:
https://ark.intel.com/products/71460/Intel-Core-i7-3635QM-Processor-6M-Cache-up-to-3-40-GHz-

**Comment by kylehovey** [comment] 2019-02-21 16:12
Ah, my processor is pre-Haswell. I had a macbook Air before this laptop that was Haswell, but "upgraded" to a higher spec earlier macbook pro. Thank you for the clarification.

**Comment by rspeed** [comment] 2019-02-21 19:11
Maybe turn this into a feature request to show a clear error when AVX2 isn't supported?

**Comment by kylehovey** [comment] 2019-02-21 19:19
That's a good idea. Also, is it possible that standard `AVX` could be used in lieu of `AVX2`? Plenty of processor arches use the former.

**Comment by kylehovey** [comment] 2019-02-21 19:20
I can't tag this as a feature request, but I updated the title to indicate that it is one.

**Comment by lemire** [comment] 2019-02-21 22:56
I added the labels.

**Comment by ScrambledAuroras** [comment] 2019-02-23 00:53
There are GCC builtins for checking AVX2, otherwise you'd have to use CPUID in x86_64 inline assembler.

```c
// https://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.htmlhttps://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.html

assert(__builtin_cpu_supports("avx2")); // if 0 then it will fail. if not 0 then it will succeed
```

If not relying on the *runtime* but on *compile-time* we use a special `__AVX2__` macro. I'll test it out on my Pentium 4.

If relying on `clang` I am not sure.

**Comment by TkTech** [comment] 2019-02-23 01:06
Clang's behaviour for `__builtin_cpu_supports` and `__AVX2__` is identical to gcc as of r240994 (~2015)

**Comment by ScrambledAuroras** [comment] 2019-02-23 01:25
I can't seem to test out the assertion that I inserted on legacy hardware because I do not have a machine from the era, so hopefully someone else can test.

I tested it on my Core i7 8th gen. Tests pass with a quickly made assertion. I can refine it later. The Pentium 4 does not compile the code, it is not 64-bit.

**Comment by cdluminate** [comment] 2019-04-19 09:14
@ScrambledAuroras Maybe you want to try QEMU, emulating a baseline CPU which doesn't support AVX2: `qemu-x86_64 -cpu qemu64 /usr/bin/some_program`

**Comment by erg** [comment] 2019-04-19 15:02
I'm reading your paper, very cool!

I tried to run it on my MacBook Pro (Retina, 13-inch, Late 2012) and it fails with:

```
% ./tools/jsonstats ~/package-lock.json
[1]    66749 illegal hardware instruction  ./tools/jsonstats ~/package-lock.json
``` 

After trying the assert line from above, I get this:

```
diff --git a/tools/jsonstats.cpp b/tools/jsonstats.cpp
index 96668e7..7ee4acd 100644
--- a/tools/jsonstats.cpp
+++ b/tools/jsonstats.cpp
@@ -128,6 +128,9 @@ int main(int argc, char *argv[]) {
   if (optind + 1 < argc) {
     std::cerr << "warning: ignoring everything after " << argv[optind + 1] << std::endl;
   }
+
+  assert(__builtin_cpu_supports("avx2"));
+
   std::string_view p;
   try {
     p = get_corpus(filename);
```

```
% ./tools/jsonstats ~/package-lock.json
Assertion failed: (__builtin_cpu_supports("avx2")), function main, file ../tools/jsonstats.cpp, line 132.
[1]    66854 abort      ./tools/jsonstats ~/package-lock.json
```


```
macOS Mojave 10.14.4 (18E226)

% clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I also tested on Arch Linux with avx2 with g++ and it compiles and works.
```
CC=gcc CXX=g++ cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..

g++ --version
g++ (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

AMD Ryzen Threadripper 2970WX 24-Core Processor
```

Hope this helps.

**Comment by lemire** [comment] 2019-04-19 16:04
@erg 

Great comment.

Yes, I would not expect a machine from 2012 to support AVX2.

**Comment by TkTech** [comment] 2019-04-19 18:59
@ScrambledAuroras @cdluminate use the Intel SDE to emulate past, current, and unreleased cpu features for a single binary. https://software.intel.com/en-us/articles/intel-software-development-emulator

**Comment by lemire** [comment] 2020-01-09 21:33
We now have runtime dispatch, so this issue is obsolete.

**Closed by lemire** 2020-01-09 21:33 UTC
Labels: feature request, good first issue, help wanted
