### ISSUE TITLE
Possible issue with decoding subnormals

### ISSUE THREAD

**Issue by Licenser** [lemire/simdjson#325] opened 2019-10-06 18:25 UTC
On simd-json.rs we discovered that `-5.96916642387374e-309` which is a valid representable floating point number couldn't get parsed. I suspect the same issue exists in simdjson.

I'll add a (possibly failing) test case and if required a fix to it later when I get around to it but  wanted to throw in an issue to keep track of it.

The change was to extend the exponent rage to `1e-323`.

**Comment by lemire** [comment] 2019-10-06 20:09
What DBL_MIN for you?

I think it should be...

2.2250738585072014e-308

My suspicion is that you are going into the subnormals.

**Comment by lemire** [comment] 2019-10-06 20:13
In Rust what is f64::MIN_POSITIVE?

**Comment by Licenser** [comment] 2019-10-06 20:16
The problem comes from how it is parsed `-5.96916642387374e-309` is parsed as `596916642387374e-323` (if I didn't miscount) and [1e-323 is still represented correctly](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b71b7a1afb523033a600cfa37d7eb0a8)

**Comment by Licenser** [comment] 2019-10-06 20:19
re-reading the current state of the c++ code I am wrong, the location the check happens moved since I translated it to rust :) so simdjson doens't have the same problem!

**Comment by lemire** [comment] 2019-10-06 22:03
Did you try to write a test? If not, I will...

**Comment by lemire** [comment] 2019-10-06 22:04
I changed the title from very small to subnormal. I think subormal is more than just very small.

**Comment by Licenser** [comment] 2019-10-07 05:08
I've not been on a workable computer yet, I'll add one when I get home tonight, kind of don't want to do it over the web interface :D

**Comment by lemire** [comment] 2019-10-07 14:09
No worries, I will check it in. It just just one new file to create.

**Comment by lemire** [comment] 2019-10-07 14:16
Let us test it out: https://github.com/lemire/simdjson/pull/328

**Comment by lemire** [comment] 2019-10-07 15:02
I merged the check and it looks fine. Please reopen if you think that the issue is still there.

**Closed by lemire** 2019-10-07 15:02 UTC
