### ISSUE TITLE
possible bug in is_valid_false_atom

### ISSUE THREAD

**Issue by Licenser** [lemire/simdjson#155] opened 2019-05-08 20:55 UTC
The `is_valid_false_atom` assigns the result of the check to a 32 bit value and cheks if it's 0;

`false` has 5 characters so the check only covers if it's a valid `fals` atom, for example `falsy` would also pass the check in question.

**Comment by lemire** [comment] 2019-05-08 21:22
Thanks. I will work on this.

**Comment by Licenser** [comment] 2019-05-08 21:24
FWIW: I found that using a 64 bit error value instead of a 32 bit one solves the issue. but I'm not sure about the negative impact on the performance of that.

**Comment by lemire** [comment] 2019-05-09 15:14
>  I'm not sure about the negative impact on the performance of that

I have not measured it, because I expect that there won't be any impact. It is going to be the same number of instructions (I expect). 

Anyhow, if you have a document where parsing "false" atoms is the bottleneck... it is going to be a fun document.

**Comment by lemire** [comment] 2019-05-09 15:14
Let us close this.

**Closed by lemire** 2019-05-09 15:14 UTC
Labels: bug, unverified

**Comment by lemire** [comment] 2019-05-09 17:06
The new code might actually be faster...

https://godbolt.org/z/ORcNo5

I'll do a performance comparison later but I am confident that there won't be a regression and there might be a small gain. In any case, it is bug fix so it is not like we can have a choice. We can't leave the old code.
