### ISSUE TITLE
Add Visual Studio 2019 Solution 

### ISSUE THREAD

**Issue by DBJDBJ** [lemire/simdjson#385] opened 2019-12-04 12:17 UTC
Single Header folder (as it stands today) was never built with VS2019 / CL ... One VS2019 solution will save you a lot of time because that will be: ready-made,  instant, no-effort way to use simdb on windows ...

**Comment by lemire** [comment] 2019-12-04 13:07
The single-header folder is not "built" normally on any platform, including Visual Studio.

It is not meant to be built. You are supposed to grab to files and integrate them into your project.

**Comment by lemire** [comment] 2019-12-04 13:08
I am going to close this issue, because I think it is properly documented in the README.

If you have specific proposals or issues, please reopen this issue and share your thoughts.

**Closed by lemire** 2019-12-04 13:08 UTC

**Comment by DBJDBJ** [comment] 2019-12-04 14:57
I am going to calmly assume you misunderstood me.

I am saying : if you do what I suggest, you will spend much less or zero time, on the issues tab, explaining to people how to build using VS2019 + CL ...

There are a lot of people (aka "very large audience") who have never used CMake and likely never will. But they are very likely to want to use your lib. On Windows. Using VS2019.

**Comment by lemire** [comment] 2019-12-04 15:33
> who have never used CMake and likely never will

I agree.

There are hundreds of different build systems. We support CMake since it is the de facto standard for cross-platform builds. It is well supported by Microsoft, among others. 

We are not going to support platform-specific or IDE-specific build systems.

Of course, *you* can provide this support. If you build a repository with an IDE-specific build system for our single-header files, we will link to it.

People who do not wish to use CMake (a very reasonable stance) should grab the single-header files and and drop them in their projects. It should be as simple as dropping two files into your project. If you have expertise in this domain, please contribute by making public a repository of your making.

The core simdjson development will continue on CMake.

> I made it work but I am doing this for decades. windows.h include requires ancient macros beforehand. One fopen had to be changed to fopen_s.

If there are issues with the code regarding either a specific supported compiler or a standard library please raise them as specific issues. Note that we already compile the library as a matter of course under Visual Studio including the IO (file access) code.

**Comment by DBJDBJ** [comment] 2019-12-04 21:43
https://github.com/dbj-systems/simd_json_visual_studio.git

Builds.  Does not run. "Kicks the bucket" at somewhat random locations ...

**Comment by lemire** [comment] 2019-12-04 22:18
From CMake, you can generate a Visual Studio file, it will build the library and you can then run the tests... we do it automatically with each commit in CI:

https://ci.appveyor.com/project/lemire/simdjson/build/job/t3d0j1rn489af2id

Our code builds under Windows and it passes our tests. And this includes file accesses.

You do not need to port the code. The portability has already been handled.

Several of our contributors work for Microsoft, the library is available via Microsoft vpkg. The library is part of Microsoft FishStore https://github.com/microsoft/FishStore

Now, of course, there might be bugs... if so report them. Don’t port the code to Visual Studio: it is wasted effort. We are committed to supporting Visual Studio.

**Comment by DBJDBJ** [comment] 2019-12-05 08:49
OK + Clear = No worries ...

**Comment by DBJDBJ** [comment] 2019-12-05 09:23
Sorry to be a proverbial pain in the ... I did a legal install .. Cmake and all that ... ALL_BUILD builds, but RUNTESTS fails. 

This machine is WIN10 PRO , i5 CPU, 8GB RAM ... this is the visual studio build dump on running building RUN_TESTS :


1>------ Build started: Project: RUN_TESTS, Configuration: Debug x64 ------
1>Test project D:/DEVL/GitHub/simdjson
1>    Start 1: basictests
1>1/5 Test #1: basictests .......................***Exception: Illegal  0.24 sec
1>    Start 2: jsoncheck
1>2/5 Test #2: jsoncheck ........................***Exception: Illegal  0.21 sec
1>    Start 3: jsonstream_test
1>3/5 Test #3: jsonstream_test ..................***Exception: Illegal  0.09 sec
1>    Start 4: pointercheck
1>4/5 Test #4: pointercheck .....................***Exception: Illegal  0.20 sec
1>    Start 5: integer_tests
1>5/5 Test #5: integer_tests ....................***Exception: Illegal  0.21 sec
1>
1>0% tests passed, 5 tests failed out of 5
1>
1>Total Test time (real) =   0.98 sec
1>
1>The following tests FAILED:
1>	  1 - basictests (ILLEGAL)
1>	  2 - jsoncheck (ILLEGAL)
1>	  3 - jsonstream_test (ILLEGAL)
1>	  4 - pointercheck (ILLEGAL)
1>	  5 - integer_tests (ILLEGAL)
1>Errors while running CTest
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: The command "setlocal
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: "C:\Program Files\CMake\bin\ctest.exe" --force-new-ctest-process -C Debug
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmEnd
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmErrorLevel
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: exit /b %1
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmDone
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>D:\PROD\programs\vs2019ide\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :VCEnd" exited with code 8.
1>Done building project "RUN_TESTS.vcxproj" -- FAILED.
Build has been canceled.
Projects build report:
  Status    | Project [Config|platform]
 -----------|---------------------------------------------------------------------------------------------------
  Succeeded | ZERO_CHECK.vcxproj [Debug|x64]
  Failed    | RUN_TESTS.vcxproj [Debug|x64]

**Comment by DBJDBJ** [comment] 2019-12-05 11:38
Yes, worries.   

Fish Store was neve built using VS 2019, too ...
As we all know: "He who uses CMake, he likes pain" ...

There are also C++03 (or is it 98?) constructs in there ... but that is another big subject ... this applies to both projects: simd JSON and FishStore ...

Please advise ...

**Comment by lemire** [comment] 2019-12-05 13:15
The simdjson library builds and runs in CI (please see the log) and it builds and run on our machines.  If you have problems building this library with Visual Studio, you need to provide enough details so that others reproduce and verify the issue.

**Comment by piotte13** [comment] 2019-12-05 16:28
CMake might be an annoying extra effort, but we could also say, as we all know: "He who uses IDE-specific build systems, likes flipping tables and kicking buckets at random locations".

**Comment by DBJDBJ** [comment] 2019-12-06 10:21
Guy from the FishStore poject is very reasonable. He will amend their readme so that cmake / vs2019 combo, will have the correct incantation.  

As of VS2019 , cmake has changed the behaviour. It appears -A switch is now required. But in reality, it is not required. Neither is the architecture code required as the last word in the command argument string ... 

```
cmake .. -G "Visual Studio 16 2019"
```

is the correct command ...  no -A required ...
